# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1465537247);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1465536458);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 0);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1465536717);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1465536578);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1465536527500");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1465538207500");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1465536457794");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1465540057794");
user_pref("browser.search.countryCode", "FR");
user_pref("browser.search.region", "FR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160607223741");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20160607223741");
user_pref("browser.startup.homepage_override.mstone", "45.2.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"pocket-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"abp-toolbarbutton\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"abp-toolbarbutton\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":5,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1465622733146");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1465536442277");
user_pref("datareporting.policy.firstRunTime", "1465536333146");
user_pref("datareporting.sessions.current.activeTicks", 18);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 4977);
user_pref("datareporting.sessions.current.main", 30);
user_pref("datareporting.sessions.current.sessionRestored", 5027);
user_pref("datareporting.sessions.current.startTime", "1465537124523");
user_pref("datareporting.sessions.current.totalTime", 165);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1465536326997,\"a\":13,\"t\":436,\"c\":true,\"m\":1144,\"fp\":55340,\"sr\":55290}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1465536816471,\"a\":0,\"t\":11,\"c\":false,\"m\":20,\"fp\":4779,\"sr\":4696}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1465536968091,\"a\":5,\"t\":29,\"c\":false,\"m\":21,\"fp\":2026,\"sr\":2254}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1465537092914,\"a\":3,\"t\":23,\"c\":true,\"m\":16,\"fp\":2343,\"sr\":2455}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.adblockplus.currentVersion", "2.7.3");
user_pref("extensions.adblockplus.notificationdata", "{\"lastCheck\":1465537278699,\"softExpiration\":1465617215397,\"hardExpiration\":1465710082007,\"data\":{\"notifications\":[],\"version\":\"201606100540\"},\"lastError\":0,\"downloadStatus\":\"synchronize_ok\",\"downloadCount\":1}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"langpack-fr@firefox-esr.mozilla.org\":{\"version\":\"45.2.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox-esr/browser/extensions/langpack-fr@firefox-esr.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"version\":\"2.7.3\",\"type\":\"extension\",\"descriptor\":\"/home/studiobox/.mozilla/firefox/qvdxhdu0.default/extensions/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.2.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1465537258);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.2.0");
user_pref("extensions.lastPlatformVersion", "45.2.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1465350136000}},\"app-global\":{\"langpack-fr@firefox-esr.mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/langpack-fr@firefox-esr.mozilla.org.xpi\",\"e\":true,\"v\":\"45.2.0\",\"st\":1465349692000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.2.0\",\"st\":1465350136000}},\"app-profile\":{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"d\":\"/home/studiobox/.mozilla/firefox/qvdxhdu0.default/extensions/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}.xpi\",\"e\":true,\"v\":\"2.7.3\",\"st\":1465537213000}}}");
user_pref("gecko.buildID", "20160607223741");
user_pref("gecko.mstone", "45.2.0");
user_pref("idle.lastDailyNotification", 1465536709);
user_pref("media.gmp-manager.buildID", "20160607223741");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1465536717);
user_pref("places.history.expiration.transient_current_max_pages", 98634);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1465536717);
user_pref("toolkit.startup.last_success", 1465537124);
user_pref("toolkit.telemetry.cachedClientID", "d43b5d92-2db5-4bb6-b3c9-39a5732a1bbc");
user_pref("toolkit.telemetry.previousBuildID", "20160607223741");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
