# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1413485699);
user_pref("app.update.lastUpdateTime.background-update-timer", 1413486028);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1413485819);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1413486148);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1330858538);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1330858555);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1413484155);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20141203154826");
user_pref("browser.slowStartup.averageTime", 18582);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20140924224142");
user_pref("browser.startup.homepage_override.mstone", "24.8.1");
user_pref("browser.tabs.autoHide", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"customizableui-special-spring1\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"unified-back-forward-button\",\"reload-button\",\"stop-button\",\"new-tab-button\",\"home-button\",\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"webrtc-status-button\",\"social-share-button\",\"window-controls\"],\"TabsToolbar\":[\"appmenu-toolbar-button\",\"tabbrowser-tabs\",\"alltabs-button\",\"tabs-closebutton\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"addon-bar\",\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"newElementCount\":1}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1413570433449");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1413484033449");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 12258);
user_pref("datareporting.sessions.current.main", 937);
user_pref("datareporting.sessions.current.sessionRestored", 12455);
user_pref("datareporting.sessions.current.startTime", "1413527990716");
user_pref("datareporting.sessions.current.totalTime", 74);
user_pref("datareporting.sessions.currentIndex", 9);
user_pref("datareporting.sessions.previous.0", "{\"s\":1413484009473,\"a\":17,\"t\":174,\"c\":true,\"m\":993,\"fp\":6604,\"sr\":42343}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1413484237386,\"a\":1,\"t\":12,\"c\":true,\"m\":21,\"fp\":3671,\"sr\":3719}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1413485578384,\"a\":39,\"t\":326,\"c\":true,\"m\":31,\"fp\":2670,\"sr\":2717}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1413485906053,\"a\":58,\"t\":1737,\"c\":true,\"m\":0,\"fp\":2149,\"sr\":2255}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1413488340138,\"a\":2,\"t\":16,\"c\":true,\"m\":31,\"fp\":741,\"sr\":799}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1413488980536,\"a\":1,\"t\":11,\"c\":true,\"m\":31,\"fp\":730,\"sr\":787}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1413490069150,\"a\":2,\"t\":29,\"c\":true,\"m\":2068,\"fp\":9180,\"sr\":9366}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1413491278269,\"a\":1,\"t\":27,\"c\":true,\"m\":944,\"fp\":5179,\"sr\":5368}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1413492398572,\"a\":2,\"t\":48,\"c\":true,\"m\":931,\"fp\":5660,\"sr\":5855}");
user_pref("extensions.adblockplus.currentVersion", "2.1");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"firefox@ghostery.com\":{\"version\":\"5.4.1\",\"type\":\"extension\",\"descriptor\":\"/home/webradio/.mozilla/firefox/default/extensions/firefox@ghostery.com.xpi\"},\"langpack-fr@iceweasel.mozilla.org\":{\"version\":\"24.8.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-fr@iceweasel.mozilla.org.xpi\"},\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"version\":\"2.1\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.3.0");
user_pref("extensions.enabledItems", "langpack-fr@firefox.mozilla.org:3.5.1036,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.16");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}\",\"mtime\":1416238167000,\"rdfTime\":1373371950000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1418033499000,\"rdfTime\":1417623051000},\"langpack-fr@iceweasel.mozilla.org\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/langpack-fr@iceweasel.mozilla.org.xpi\",\"mtime\":1417623246000}}},{\"name\":\"app-profile\",\"addons\":{\"firefox@ghostery.com\":{\"descriptor\":\"/home/webradio/.mozilla/firefox/default/extensions/firefox@ghostery.com.xpi\",\"mtime\":1418032533000}}}]");
user_pref("extensions.lastAppVersion", "31.3.0");
user_pref("extensions.lastPlatformVersion", "31.3.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", false);
user_pref("gecko.buildID", "20141203154826");
user_pref("gecko.mstone", "31.3.0");
user_pref("idle.lastDailyNotification", 1413486409);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1413486412);
user_pref("places.history.expiration.transient_current_max_pages", 98700);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1413486410);
user_pref("toolkit.startup.last_success", 1418035529);
user_pref("toolkit.telemetry.previousBuildID", "20141203154826");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1416076068);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
